name: Tutor CI

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:tutor-experience
      - name: Deploy to S3
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: ./dist/apps/tutor-experience
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
